# Project information
site_name: Librechat
docs_dir: .

# Repository
repo_name: danny-avila/LibreChat
repo_url: https://github.com/danny-avila/LibreChat

theme:
  name: material
  logo: assets/logo.png
  
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  
  icon:
    repo: fontawesome/brands/gitlab
    edit: material/pencil
    view: material/eye
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.action.edit
    - content.code.copy

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


# Page tree
nav:
  - Home: 'README.md'
  - Getting Started: 
    - Docker Install: 'docs/install/docker_install.md'
    - Linux Install: 'docs/install/linux_install.md'
    - Mac Install: 'docs/install/mac_install.md'
    - Windows Install: 'docs/install/windows_install.md'
    - APIs and Tokens: 'docs/install/apis_and_tokens.md'
  - General Information:
    - Code of Conduct: 'CODE_OF_CONDUCT.md'
    - Project Origin: 'docs/general_info/project_origin.md'
    - Multilingual Information: 'docs/general_info/multilingual_information.md)'
    - Tech Stack: 'docs/general_info/tech_stack.md'
    - Bing Jailbreak Info: 'docs/general_info/bing_jailbreak_info.md'
  - Features:
    - Plugins:
      - Introduction]: 'docs/features/plugins/introduction.md'
      - Google: 'docs/features/plugins/google_search.md'
      - Stable Diffusion: 'docs/features/plugins/stable_diffusion.md'
      - Wolfram: 'docs/features/plugins/wolfram.md'
      - Make Your Own Plugin: 'docs/features/plugins/make_your_own.md'
    - User Auth System: 'docs/features/user_auth_system.md'
    - Proxy: 'docs/features/proxy.md'
  - Cloud Deployment:
    - Hetzner: 'docs/deployment/hetzner_ubuntu.md'
    - Heroku: 'docs/deployment/heroku.md'
  - Contributions:
    - Contributor Guidelines: 'CONTRIBUTING.md'
    - Documentation Guidelines: 'docs/contributions/documentation_guidelines.md'
    - Code Standards and Conventions: 'docs/contributions/coding_conventions.md'
    - Testing: 'docs/contributions/testing.md'
    - Security: 'SECURITY.md'
    


  
