name: Lint for accessibility issues

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  axe-linter:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'a11y')
    
    steps:
      - uses: actions/checkout@v4
      - uses: dequelabs/axe-linter-action@v1
        with:
          api_key: ${{ secrets.AXE_LINTER_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}