name: Backend Unit Tests
on:
  push:
    branches:
      - main
      - dev
      - release/*
  pull_request:
    branches:
      - main
      - dev
      - release/*
jobs:
  tests_Backend:
    name: Run Backend unit tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CREDS_KEY: ${{ secrets.CREDS_KEY }}
      CREDS_IV: ${{ secrets.CREDS_IV }}
      APP_TITLE: 'Test Title'
      GOOGLE_CLIENT_ID: 'Test Google Client Id'
      GOOGLE_CLIENT_SECRET: 'Test Google Client Secret'
      DOMAIN_SERVER: 'http://test-server.com'
      ALLOW_REGISTRATION: 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # - name: Install Linux X64 Sharp
      #   run: npm install --platform=linux --arch=x64 --verbose sharp

      - name: Run unit tests
        run: cd api && npm run test:ci
