
name: Backend Unit Tests
on:
  push:
    branches: [feat/playwright-jest-cicd]
  pull_request:
    branches: [ feat/playwright-jest-cicd ]
jobs:
  tests_Backend:
    name: Run Backend unit tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run unit tests
        run: npm run test