name: Download and Push Translations

# You can trigger this workflow on a schedule, on push to a specific branch,
# or even manually. Here we trigger it on push to main.
on:
  push:
    branches:
      - main

jobs:
  download-and-commit:
    name: Download and Commit Translations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download translations from locize
        uses: locize/download@v1
        with:
          project-id: ${{ secrets.LOCIZE_PROJECT_ID }}

      - name: Commit and Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update translations from locize"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}