name: Generate Unreleased Changelog PR

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  generate-unreleased-changelog-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Required for pushing new branches and commits.
      pull-requests: write
    steps:
      # 1. Checkout the repository with full history.
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Get the latest version tag (to compare against).
      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag: $LATEST_TAG"
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      # 3. Generate the Unreleased changelog.
      - name: Generate Unreleased Changelog
        id: generate_unreleased
        uses: mikepenz/release-changelog-builder-action@v5.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: ".github/configuration-unreleased.json"
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          outputFile: CHANGELOG-unreleased.md
          fromTag: ${{ steps.get_latest_tag.outputs.tag }}
          toTag: main

      # 4. Update (or create) CHANGELOG.md with the new Unreleased section.
      - name: Update CHANGELOG.md with new Unreleased section
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "CHANGELOG.md not found. Creating a new one..."
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
            echo "All notable changes to this project will be documented in this file." >> CHANGELOG.md
            echo "" >> CHANGELOG.md
            # Append the freshly generated Unreleased changelog.
            cat CHANGELOG-unreleased.md >> CHANGELOG.md
          else
            echo "Updating existing CHANGELOG.md…"
            # If an "Unreleased" section exists, split based on it.
            if grep -q "^## \[Unreleased\]" CHANGELOG.md; then
              awk '/^## \[Unreleased\]/{exit} {print}' CHANGELOG.md > header.md
              awk 'flag{print} /^---/{flag=1; print}' CHANGELOG.md > tail.md
            else
              # Otherwise, split using the first release header (assumed to start with "## [v")
              awk '/^## \[v/{exit} {print}' CHANGELOG.md > header.md
              awk 'f{print} /^## \[v/{f=1; print}' CHANGELOG.md > tail.md
            fi
            # Combine header, new Unreleased changelog, and tail.
            cat header.md CHANGELOG-unreleased.md tail.md > CHANGELOG.md.new
            mv CHANGELOG.md.new CHANGELOG.md
          fi
          echo "Final CHANGELOG.md:"
          cat CHANGELOG.md

      # 5. Commit the updated or new CHANGELOG.md.
      - name: Commit changes
        run: |
          git add CHANGELOG.md
          git commit -m "action: update Unreleased changelog" || echo "No changes to commit"

      # 6. Create a pull request using a unique branch name.
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sign-commits: true
          commit-message: "action: update Unreleased changelog"
          base: main
          # Use a unique branch name (using the run ID ensures no prior branch exists).
          branch: "changelog/unreleased-update-${{ github.run_id }}"
          title: "action: update Unreleased changelog"
          body: |
            **Description**:
            - This PR introduces (or updates) the CHANGELOG.md file with the new Unreleased section.
            - It compares the current main branch with the latest version tag (${{ steps.get_latest_tag.outputs.tag }}),
              regenerates the Unreleased changelog, and then creates a commit that adds the new file if it was deleted.