name: Build Helm Charts on Tag

# Trigger the workflow when a tag is pushed.
on:
  push:
    tags:
      - "*"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Lint Helm Chart
        run: helm lint charts/librechat

      - name: Package Helm Chart
        run: helm package charts/librechat --destination ./packages

      - name: Update Helm Repository Index
        run: |
          # Copy artifacthub-repo.yml to the packages folder so it’s served with the index.
          cp artifacthub-repo.yml ./packages/
          helm repo index ./packages --url https://danny-avila.github.io/LibreChat

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages